# Create a new user
POST http://localhost:3000/api/auth/register HTTP/1.1
Content-Type: application/json

{
  "email": "user2@notfound.local",
  "avatar": "http://avatar.ru/1.jpg",
  "name": "Keks",
  "password": "123456"
}

###

GET http://localhost:3000/api/auth/677cd8d75ff92067f1de5911 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NzdjZDhkNzVmZjkyMDY3ZjFkZTU5MTEiLCJlbWFpbCI6InVzZXIyQG5vdGZvdW5kLmxvY2FsIiwibmFtZSI6Iktla3MiLCJpYXQiOjE3MzYyMzU1MTksImV4cCI6MTczNjI2NTUxOX0.C0HDshSggKAuCjqcIgqMuDx18FcYDMsLciifJpVgrPU

###

# Login user by email and password
POST http://localhost:3000/api/auth/login HTTP/1.1
Content-Type: application/json

{
  "email": "user2@notfound.local",
  "password": "123456"
}

###
# Get new JWT pair
POST http://localhost:3000/api/auth/refresh HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InVzZXJAbm90Zm91bmQubG9jYWwiLCJyb2xlIjoidXNlciIsImxhc3RuYW1lIjoiU21pdGgiLCJmaXJzdG5hbWUiOiJLZWtzIiwiaWF0IjoxNzA1NjgwMDA4LCJleHAiOjE3MDgyNzIwMDh9.10Jr7bWOiFTTi42JcMgPh0GVbxa2ikvn8vUVcF8d-AY

###
# Check user token
POST http://localhost:3000/api/auth/check HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NzdjZDhkNzVmZjkyMDY3ZjFkZTU5MTEiLCJlbWFpbCI6InVzZXIyQG5vdGZvdW5kLmxvY2FsIiwibmFtZSI6Iktla3MiLCJpYXQiOjE3MzYyMzU1MTksImV4cCI6MTczNjI2NTUxOX0.C0HDshSggKAuCjqcIgqMuDx18FcYDMsLciifJpVgrPU

###
