version: '3.9'
services:
  shop.notify.fakesmtp:
    image: gessnerfl/fake-smtp-server:2.2.0
    container_name: 'shop.notify.fakesmtp'
    hostname: 'shop.notify.fakesmtp'
    ports:
      - ${MAIL_SMTP_PORT}:${MAIL_SMTP_PORT}
      - '1085:8080'

  shop.notify.rabbitmq:
    image: rabbitmq:3.11-management
    container_name: shop.notify.rabbitmq

    ports:
      - '1088:15672'
      - '5672:5672'

    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}

    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 10s
      timeout: 5s
      retries: 5
